astra:
  api:
    application-token: ENC(SyjL8PGxBu2FG58sS8QgvYM5ED1oaznEzjItP36GEcbrRs7ZT9iP91teRrHcv+3SEPXWXagtBcpLMP2qZMoUAyNnM1bC5FuK8NVf5r5hFSbMtzq20QBzoUH3TXcfJxkuV4n9ezQ09IMFnQ3mcVn8kA==)
    database-id: b102fdff-a68f-4c11-a9da-e5c6c51025e2
    database-region: asia-south1
    grpc:
      enabled: true
  cql:
    enabled: true
    download-scb:
      # if disabled zip files must be in folder (path)
      enabled: true
      # Looking for files scb_dbid-dbregion.zip in folder (default is ~/.astra/scb)
      # path: /tmp
    driver-config:
      basic:
        session-keyspace: master
        request:
          timeout: 30s
spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:10003/evernotedata?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: sudhir
    password: ENC(fIEwy2BmSBDfu8/OP60hflNTm//seUbT)
    testOnBorrow: true
    validationQuery: SELECT 1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: evernote-reporting-app
  data:
    cassandra:
      schema-action: CREATE_IF_NOT_EXISTS
jasypt:
  encryptor:
    password: ${ENCRYPTION_CODE}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator    